name: testdelGHCR

on:
  workflow_dispatch:
    # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # This is the key permission
    steps:      
    # Login to GitHub Container Registry (ghcr)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Delete old image versions
      uses: actions/delete-package-versions@v5
      with:
        package-name: ${{ github.event.repository.name }}
        package-type: 'container'
        min-versions-to-keep: 1
        owner: ${{ github.repository_owner }}
        delete-only-untagged-versions: 'false'
